### ISSUE TITLE
cannot snap-exec: cannot exec "/snap/ruby/200/bin/bundle": permission denied

### ISSUE THREAD

**Issue by znz** [ruby/snap.ruby#23]
`bundle` of snap ruby 3.0.0  2020-12-26 (200) does not work.

```console
vagrant@buster:~$ PATH=/snap/bin:$PATH
vagrant@buster:~$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
vagrant@buster:~$ bundle
cannot snap-exec: cannot exec "/snap/ruby/200/bin/bundle": permission denied
```

The shebang may be wrong.

```console
vagrant@buster:~$ head -n1 /snap/ruby/[12]*/bin/bundle
==> /snap/ruby/189/bin/bundle <==
#!/snap/ruby/current/bin/ruby
==> /snap/ruby/200/bin/bundle <==
#!/root/parts/ruby/install//bin/ruby
```

**Comment by hsbt** [comment]
@znz Thanks.

I fixed it 201 revision. Can you try with 201?

```
ubuntu@primary:~$ head -1 /snap/ruby/201/bin/bundle
#!/snap/ruby/current/bin/ruby
```

**Comment by znz** [comment]
201's bundle failed with another error.

```console
vagrant@buster:~$ bundle init
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:43:in `<top (required)>': uninitialized constant Gem::BasicSpecification (NameError)
	from /snap/ruby/201/lib/ruby/3.0.0/rubygems.rb:1348:in `require'
	from /snap/ruby/201/lib/ruby/3.0.0/rubygems.rb:1348:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
```

**Comment by hsbt** [comment]
It seems mixed with rubygems provided debian package.

**Comment by znz** [comment]
After `export DEBIAN_DISABLE_RUBYGEMS_INTEGRATION=true` and `bundle install` again, it resolved. thanks.

**Comment by hsbt** [comment]
It's nice to add `DEBIAN_DISABLE_RUBYGEMS_INTEGRATION=1` to wrapper files of snap package, I think.
